<a href="https://colab.research.google.com/github/Youmn97Hussien/Linear_Regression-/blob/main/linear%20regression%20with%20sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
from tensorflow import keras
from keras.datasets import mnist
from sklearn.linear_model import LinearRegression

(X_Train, Y_Train) , (X_Test, Y_Test)= mnist.load_data()


In [36]:
def preprocess_Data(X_Train, Y_Train, X_Test, Y_Test):
  # reshape dataset from 3D to 2D
  X_Train_Samples,  X_Train_featuersR, X_Train_featuersC = X_Train.shape
  X_Train = X_Train.reshape(X_Train_Samples, X_Train_featuersR * X_Train_featuersC)  

  X_Test_Samples,   X_Test_featuersR,  X_Test_featuersC =  X_Test.shape
  X_Test = X_Test.reshape(X_Test_Samples, X_Test_featuersR * X_Test_featuersC )  
  print(X_Test.shape)
  return X_Train, Y_Train, X_Test, Y_Test

In [37]:
def Train_LinearRegression(X_Train, Y_Train):
  return

In [38]:
def Calssify_LinearRegression(X_Test, Y_Test):
  return

In [39]:
# Main Calling
preprocess_Data(X_Train, Y_Train, X_Test, Y_Test) 

(10000, 784)


(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([5, 0, 4, ..., 5, 6, 8], dtype=uint8),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([7, 2, 1, ..., 4, 5, 6], dtype=uint8))